-- AUTOR: LILI MP
-- NC TRAINEE PROGRAM
-- FINAL PROYECT: RENT A CAR "TRIPS BY WHEELS"

 USE  VEHICLES;

-- DELETE FROM VEHICLES WHERE NUMBER_PLATE = 0;
-- INSERTANDO 6 AVEO AUTOMATICOS
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'AVEO', 'AUTOMATIC', 5, 1, 700.00);

-- INSERTANDO 6 AVEO ESTANDAR
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'AVEO', 'MANUAL', 5, 1, 675.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'AVEO', 'MANUAL', 5, 1, 675.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'AVEO', 'MANUAL', 5, 1, 675.00);

-- INSERTANDO 3 ONIX AUTOMATICOS
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'ONIX', 'AUTOMATIC', 5, 1, 750.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'ONIX', 'AUTOMATIC', 5, 1, 750.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'ONIX', 'AUTOMATIC', 5, 1, 750.00);

-- INSERTANDO 3 ONIX ESTANDAR
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'ONIX', 'MANUAL', 5, 1, 735.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'ONIX', 'MANUAL', 5, 1, 735.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SEDAN', 'ONIX', 'MANUAL', 5, 1, 735.00);

-- INSERTANDO 3 BEAT AUTOMATICOS
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'AUTOMATIC', 4, 1, 650.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'AUTOMATIC', 4, 1, 650.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'AUTOMATIC', 4, 1, 650.00);

-- INSERTANDO 4 BEAT ESTANDAR
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'MANUAL', 4, 1, 610.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'MANUAL', 4, 1, 610.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'MANUAL', 4, 1, 610.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'MANUAL', 4, 1, 610.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'HATCHBACK', 'BEAT', 'MANUAL', 4, 1, 610.00);

-- INSERTANDO 3 SUBURBAN 
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SUV', 'SUBURBAN', 'AUTOMATIC', 8, 1, 4474.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SUV', 'SUBURBAN', 'AUTOMATIC', 8, 1, 4474.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SUV', 'SUBURBAN', 'AUTOMATIC', 8, 1, 4474.00);

-- INSERTANDO 3 CAPTIVAS AUTOMATICAS
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SUV-LIGHT', 'CAPTIVA', 'AUTOMATIC', 7, 1, 4052.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SUV-LIGHT', 'CAPTIVA', 'AUTOMATIC', 7, 1, 4052.00);
INSERT INTO VEHICLES VALUES (0, 'CHEVROLET', 'SUV-LIGHT', 'CAPTIVA', 'AUTOMATIC', 7, 1, 4052.00);

-- BRAND: NISSAN

-- INSERTANDO 3 VERSA AUTOMATICOS
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SEDAN', 'VERSA', 'AUTOMATIC', 5, 1, 1920.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SEDAN', 'VERSA', 'AUTOMATIC', 5, 1, 1920.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SEDAN', 'VERSA', 'AUTOMATIC', 5, 1, 1920.00);

-- INSERTANDO 3 VERSA ESTANDAR
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SEDAN', 'VERSA', 'MANUAL', 5, 1, 762.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SEDAN', 'VERSA', 'MANUAL', 5, 1, 762.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SEDAN', 'VERSA', 'MANUAL', 5, 1, 762.00);

-- INSERTANDO 3 MARCH AUTOMATICOS
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'AUTOMATIC', 5, 1, 977.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'AUTOMATIC', 5, 1, 977.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'AUTOMATIC', 5, 1, 977.00);

-- INSERTANDO 4 MARCH ESTANDAR
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'MANUAL', 5, 1, 712.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'MANUAL', 5, 1, 712.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'MANUAL', 5, 1, 712.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'HATCHBACK', 'MARCH', 'MANUAL', 5, 1, 712.00);

-- INSERTANDO 2 X-TRAIL
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SUV-LIGHT', 'X-TRAIL', 'AUTOMATIC', 5, 1, 3683.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'SUV-LIGHT', 'X-TRAIL', 'AUTOMATIC', 5, 1, 3683.00);

-- INSERTANDO 3 KICKS
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'B-SUV', 'KICKS', 'AUTOMATIC', 5, 1, 2698.00);
INSERT INTO VEHICLES VALUES (0, 'NISSAN', 'B-SUV', 'KICKS', 'AUTOMATIC', 5, 1, 2698.00);

-- BRAND VOLKSWAGEN

-- INSERTANDO 3 JETTA AUTOMATICOS
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SEDAN', 'JETTA', 'AUTOMATIC', 5, 1, 1398.00);
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SEDAN', 'JETTA', 'AUTOMATIC', 5, 1, 1398.00);
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SEDAN', 'JETTA', 'AUTOMATIC', 5, 1, 1398.00);

-- INSERTANDO 3 JETTA STANDAR
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SEDAN', 'JETTA', 'MANUAL', 5, 1, 1088.00);
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SEDAN', 'JETTA', 'MANUAL', 5, 1, 1088.00);
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SEDAN', 'JETTA', 'MANUAL', 5, 1, 1088.00);

-- INSERTANDO 2 TIGUAN
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SUV-LIGHT', 'TIGUAN', 'AUTOMATIC', 7, 1, 3598.00);
INSERT INTO VEHICLES VALUES (0, 'VOLKSWAGEN', 'SUV-LIGHT', 'TIGUAN', 'AUTOMATIC', 7, 1, 3598.00);

-- BRAND: MAZDA

-- INSERTANDO 4 MAZDA CX-9
INSERT INTO VEHICLES VALUES (0, 'MAZDA', 'SUV-INTERMEDIATE', 'TIGUAN', 'AUTOMATIC', 7, 1, 4576.00);
INSERT INTO VEHICLES VALUES (0, 'MAZDA', 'SUV-INTERMEDIATE', 'TIGUAN', 'AUTOMATIC', 7, 1, 4576.00);
INSERT INTO VEHICLES VALUES (0, 'MAZDA', 'SUV-INTERMEDIATE', 'TIGUAN', 'AUTOMATIC', 7, 1, 4576.00);
INSERT INTO VEHICLES VALUES (0, 'MAZDA', 'SUV-INTERMEDIATE', 'TIGUAN', 'AUTOMATIC', 7, 1, 4576.00);





