SELECT * FROM sistema.gamma_vehicles;

INSERT INTO GAMMA_VEHICLES VALUES ('SEDAN', 'ESPACIO Y COMODIDAD A UN EXCELENTE PRECIO. TAMAÑO IDEAL PARA AQUELLOS SUELEN VIAJAR CON MUCHO EQUIPAJE.');
INSERT INTO GAMMA_VEHICLES VALUES ('HATCHBACK', 'COMODIDAD Y PRACTICIDAD EN EL MISMO LUGAR. TAMAÑO IDEAL PARA AQUELLOS QUE VIAJAN LIGERO.');
INSERT INTO GAMMA_VEHICLES VALUES ('SUV-LIGHT', 'ESPACIO Y LUJO EN UNA MISMA CAMIONETA. IDEAL PARA QUIENES DISFRUTAN DE LA ELEGANCIA A UN PRECIO ACCESIBLE.');
INSERT INTO GAMMA_VEHICLES VALUES ('B-SUV', 'CAMIONETA PEQUEÑA PERO LLENA DE LUJO. SI ESTAR A LA MODA ES LO TUYO, ENTONCES ESTA GAMMA ES JUSTO PARA TI.');
INSERT INTO GAMMA_VEHICLES VALUES ('SUV-INTERMEDIATE', 'IDEAL PARA FAMILIAS DE 5 A 7 INTEGRANTES. EL ESPACIO Y COMODIDAD NO SERÁN UN IMPEDIMENTO PARA DISFRUTAR DE TUS VIAJES.');
INSERT INTO GAMMA_VEHICLES VALUES ('SUV', 'IDEAL PARA FAMILIAS GRANDES. CON ESTE MODELO TODOTERRENO PODRÁS VIAJAR SIN PREOCUPACIONES, DE FORMA CÓMODA PERO LLENA DE LUJO Y SEGURIDAD.');